[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "SpecSMC"
dynamic = ["version"]
authors = [
    { name = "Bruker BioSpin", email = "yen-chun.huang@bruker.com" },
]
description = "A Python package for controlling the probe iris and QLP probes in Bruker BioSpin spectrometers."
readme = "README.md"
license = "GPL-3.0-only"
license-files = ["LICENSE"]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "pyserial >= 3.5",
]

[project.urls]
"Source Code" = "https://github.com/spinlaboratory/SpecSMC"

[project.scripts]
SpecSMC = "SpecSMC.cli:main"
SpecSMC-gui = "SpecSMC.gui:main"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
SpecSMC = ["config/default_config.json"]

[tool.setuptools.dynamic]
version = { attr = "SpecSMC.version.__version__" }
